services:
  - type: web
    name: rhbots-admin
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "tools.admin:crear_app()"
    envVars:
      - key: RHBOTS_SECRET
        generateValue: true
      - key: RHBOTS_GIT_PUSH
        value: "1"
      - key: RHBOTS_HTTPS
        value: "1"
      - key: GITHUB_TOKEN
        sync: false
      - key: RHBOTS_PASSWORD_HASH
        sync: false
